package com.beyondar.android.view;

import java.util.ArrayList;

import com.beyondar.android.world.BeyondarObject;

public interface OnClikBeyondarObjectListener {

	static final String __ON_CLICK_BEYONDAR_OBJECT_METHOD_NAME__ = "onClikBeyondarObject";

	/**
	 * This method is called when the user click on a {@link BeyondarObject}
	 * 
	 * @param beyondarObjects
	 *            All the {@link BeyondarObject} that collide with the ray
	 *            generated by the user click
	 */
	public void onClikBeyondarObject(ArrayList<BeyondarObject> beyondarObjects);

}